import Head from "next/head";
import Image from "next/image";
import amazonLogo from "../public/amazon_logo.svg"

export default function Title(){
    return (
        <div className="titleContent">
            <Head>
                <title>Amazon Price Guesser</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='title'>
                <Image src={amazonLogo} alt="Amazon" style={{height:'80px',width:'auto'}}/>
                <h1>Price Guessing Game</h1>
            </div>
        </div>
    )
}